# Page settings

baseURL = "https://nerwinhernando.github.io/"
languageCode = "en"
title = ""
theme = "hugo-devresume-theme"
googleAnalytics = "UA-XXXXXXX-Y"
publishDir = "nerwinhernando.github.io"





[params]
    author = "CowboySmall"
    description = "DeveloperResume - Bootstrap 4 Resume/CV Template For Software Developers"


    #primaryColor = "#54B689"
    #textPrimaryColor = "#292929"

    #primaryColor = "#950740"
    primaryColor = "#C3073F"
    textPrimaryColor = "#4E4E50"


    [params.profile]
        enable = true
        name = "Nerwin Hernando"
        tagline = "Senior Software Engineer"
        #avatar = "avatar.png"
        avatar = "avatar.jpg"







    [params.contact]
        enable = true
        location = "Manila"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:#"
        text = "+63 917 593 2711"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:#"
        text = "nerwinc.hernando@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "#"
        text = "www.yourwebsite.com"







    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Technical"
        [[params.skills.list.items]]
        details = "Unix C++"
        [[params.skills.list.items]]
        details = "Java"
        [[params.skills.list.items]]
        details = "JavaScript/React"
        [[params.skills.list.items]]
        details = "Python/Ruby"
        [[params.skills.list.items]]
        details = "Node.js/ASP.NET"
        [[params.skills.list.items]]
        details = "PostgreSQL/MySQL"
        [[params.skills.list.items]]
        details = "Object-oriented design"
        [[params.skills.list.items]]
        details = "Design and implement database structures"
        [[params.skills.list.items]]
        details = "Lead and deliver complex software systems"

        [[params.skills.list]]
        title = "Professional"
        [[params.skills.list.items]]
        details = "Effective communication"
        [[params.skills.list.items]]
        details = "Team player"
        [[params.skills.list.items]]
        details = "Strong problem solver"
        [[params.skills.list.items]]
        details = "Good time management"








    [params.education]
        enable = true

        [[params.education.list]]
        degree = "BS in Computer Science"
        university = "Adamson University"
        dates = "2001 - 2005"







    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Award Lorem Ipsum"
        body = "Microsoft lorem ipsum"
        date = "2019"
        [[params.awards.list]]
        name = "Award Donec Sodales"
        body = "Oracle Aenean"
        date = "2017"








    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "English"
        level = "Native"
        [[params.languages.list]]
        name = "Filipino"
        level = "Native"
        [[params.languages.list]]
        name = "Japanese"
        level = "Basic"








    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Climbing"
        [[params.interests.list]]
        name = "Guitar"
        [[params.interests.list]]
        name = "Badminton"
        [[params.interests.list]]
        name = "Reading"








    [params.summary]
        enable = true
        text = "Analytical and innovative software developer with 14 years of combined experience. Possesses a higher and more complex level of understanding in designing module and its interface with others. Passionate developer with an appetite for technology. Independent, resourceful, self-reliant, responsible and self-motivated. Love learning and applying design patterns in solving requirements."








    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "Ruby on Rails Developer"
        dates = "2017 - 2019"
        company = "Assembly Payments"
        #details = "As a developer joining the company without prior professional experience in RoR, I was able to perform my role by using my experience as a polyglot developer."
        [[params.experience.list.items]]
        details = "Test Driven Development using Rspec and Jest"
        [[params.experience.list.items]]
        details = "Lead local team in handling our Looker projects which is a tool used for Business Intelligence."

        [[params.experience.list]]
        title = "R&D Engineer"
        dates = "2013 - 2017"
        company = "Nokia Networks"
        #details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Donec pede justo, fringilla vel."
        [[params.experience.list.items]]
        details = "Developed features of different applications for detecting faults and alarms of equipment for log collection and analysis that are deployed in networks for Big Data and Analytics."
        [[params.experience.list.items]]
        details = "Collection of customer data from different operator’s network into Nokia Big Data and Analytics."
        [[params.experience.list.items]]
        details = "Handled modules related to Diameter Protocol and its interfaces"

        [[params.experience.list]]
        title = "Senior Software Engineer"
        dates = "2010 - 2013"
        company = "Accenture, Inc"
        [[params.experience.list.items]]
        details = "Performed creation of technical design documents, detailed design documents, development, unit testing, integration testing and code reviews."
        [[params.experience.list.items]]
        details = "Designer for building batch applications written in Visual Basic 6 to process customer data that are scheduled configurately"
        [[params.experience.list]]
        title = "Software Engineer II"
        dates = "2013 - 2014"
        company = "Redmap Networks Asia, Inc"
        #details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
        [[params.experience.list.items]]
        details = "Maintained applications for registering/unregistering Redmap Products."
        [[params.experience.list.items]]
        details = "Developed and maintained websites for licensing and automatic updates of Redmap products"

        [[params.experience.list]]
        title = "Senior Software Development Engineer"
        dates = "2014 - 2016"
        company = "Alson/AWS ISI"
        #details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus."
        [[params.experience.list.items]]
        details = "Performed unit testing, component testing, debugging and development."
        [[params.experience.list.items]]
        details = "C++ Developer/Debugger/Tester for Multi-Functional Printers (MFP)"

        [[params.experience.list]]
        title = "Design Engineer"
        dates = "2013 - 2014"
        company = "Tsukiden Software Philippines, Inc"
        #details = "Role description goes here ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus."
        [[params.experience.list.items]]
        details = "Designed and developed new features of the simulator for Diameter Protocol"
        [[params.experience.list.items]]
        details = "Performed unit and integration testing on modules assigned"
        [[params.experience.list.items]]
        details = "Developed scripts for the automation of integration and stability testing"
        [[params.experience.list.items]]
        details = "Assisted in all phases of the project life cycle from collecting user requirements, preparing program specifications, coding, testing, and debugging"
        [[params.experience.list.items]]
        details = "Managed the porting of SIP application running on Solaris platform to Linux"
        [[params.experience.list.items]]
        details = "Test and verify the operability of DoJa using i-mode in various FOMA 3G mobile phones such as N700i (NEC) and F700i (Fujitsu) in Japan"











    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "JuanaTrip"
        meta = "Not Open Source"
        tagline = "Application for booking transportation, accommodation, tour, services. I have built backend REST API’s for each service."

        [[params.projects.list]]
        title = "Prisme"
        meta = "Not Open Source"
        tagline = "Prisme General Trading LLC is a young and dynamic company based in Business Bay, Dubai. Supplying high quality products from tableware to guest room supplies and more."

        [[params.projects.list]]
        title = "Beep a Ride"
        meta = "Not Open Source"
        tagline = "Booking of rental cars."










    [params.information]
        enable = false

        [[params.information.list]]
        title = "Papers"
        [[params.information.list.items]]
        details = "2018 · Lorem Ipsum"
        [[params.information.list.items]]
        details = "2016 · Sed Fringilla"

        [[params.information.list]]
        title = "Interests"
        details = "Climbing, Snowboarding, Photography, Travelling"








    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "//github.com/nerwinhernando"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "//linkedin.com/in/nerwin-hernando-95900812/"
        title = "username"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "//twitter.com/nerwin_"
        title = "@username"





